baseURL = "/"
languageCode = "en-us"
title = "Wotecki et al. (2020) - Annual Review of Nutrition - Supplementary Materials"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = "Impacts and Echoes: The Lasting Influence of the 1969 White House Conference on Food, Nutrition and Health"
    logo = "favicon/ARN-logo.jpeg"
    githubUsername = "brandonleekramer"
    accent = "#005959" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Heebo" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/description/"
    name = "Project Description"
    weight = 2

#[[menu.main]]
#    url = "/timelines.html/"
#    name = "Timelines"
#    weight = 3
   
#[[menu.main]]
#    url = "/text-network/"
#    name = "Text Network"
#    weight = 4

#[[menu.main]]
#    url = "/text-analysis/"
#    name = "Text Analysis"
#    weight = 5
    
[[menu.main]]
    url = "/analyses/"
    name = "Supplementary Analyses"
    weight = 3
    
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://www.annualreviews.org/journal/nutr"
    name = "fas fa-book"
    weight = 1

[[menu.icon]]
    url = "https://harvard.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0efe988f-6903-46c6-bd91-aac30132f108"
    name = "fas fa-video"
    weight = 2

[[menu.icon]]
    url = "https://sites.tufts.edu/foodnutritionandhealth2019/"
    name = "fas fa-archway"
    weight = 3

[[menu.icon]]
    url = "https://github.com/uva-bi-sdad/impacts-and-echoes"
    name = "fab fa-github"
    weight = 4
    
[[menu.icon]]
    url = "mailto:brandonleekramer@gmail.com"
    name = "far fa-envelope"
    weight = 5